version: '3'
services:
  openemr:
    restart: always
    build: openemr/
    ports:
    - 80:80
    volumes:
    - logvolume01:/var/log
    - sitevolume:/var/www/localhost/htdocs/openemr/sites/default
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASS: root
      MYSQL_USER: root
      MYSQL_PASS: root
      OE_USER: admin
      OE_PASS: pass
    links:
    - mysql
  mysql:
    restart: always
    command: ['mysqld', '--character-set-server=utf8']
    build: mysql/
    volumes:
    - sqlbackup:/mnt/backups
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  sqlbackup: {}
  logvolume01: {}
  sitevolume: {}
